spring:

 output:
  ansi:
   enabled: always

 datasource:
   url: jdbc:h2:tcp://localhost/./datajpa
   username: sa
   password:
   driver-class-name: org.h2.Driver

 data:
   web:
     pageable:
       default-page-size: 10 # 1개의 page 사이즈
       max-page-size: 2000 #1개의 page의 최대 사이즈


 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    #show_sql: true #이 부분을 주석 처리한 이유는 아래의 loggig.level.org.hibernate.sql: debug에서 SQL문을 콘솔이 아니라 [로그 파일]로 남기기 위함이다.
    format_sql: true # SQL문을 보여줄 때, 한 줄로 막 보여주는 게 아니라, 이쁘게 해서 보여주는 기능11231


logging.level:
  org.hibernate.SQL: debug # 이렇게 하면,hibernate가 날리는 SQL문을 [콘솔창]이 아니라, [로그 파일]로 남길 수가 있다.
  #org.hibernate.type: trace # 이건 쿼리 파마미터(? 부분)에 어떤 데이터가 들어 갔는지 보여주는 옵션이다.
